### ISSUE TITLE
AI prompting: Agregar OAs (para Dataverse)

### ISSUE THREAD

**Issue by merunga** [Laboratoria/curriculum#1510]
Podemos usar esto para tener ideas 

- https://learnprompting.org/es/docs/intro
- https://roadmap.sh/prompt-engineering

y agregar lo a yaml de objetivos.
Ejemplo estructura de OAs aqui https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/es.yml y la data https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/data.yml

**Comment by unjust** [comment]
Algunas conceptos que puede ser objetivos que ellas van a aprender:

```
prompting:
  title: Uso de ai para generar data, imagenes etc
  links:
    - title: Learning prompting
      url: https://learnprompting.org/
 prompting/prompt-engineering
     - title: "prompt engineering (refining prompt over time) "
      url:   https://learnprompting.org/docs/basics/prompt_engineering
```

-  prompting/giving-instructions
- prompting/assigning-roles
- prompting/priming-chatbots
- prompting/applications/structuring-data
- prompting/applications/roles
- prompting/applications/chatbot
- prompting/applications/image-prompting

**Comment by merunga** [comment]
no me metería con image prompting ahora, no es el foco

De https://learnprompting.org jalaría esto
![image](https://github.com/Laboratoria/bootcamp/assets/211721/15301d3a-3ff2-4c68-9b9e-0a29528da83c)

**Comment by unjust** [comment]
Si quedamos con techniques seria : giving instructions, assigning roles, showing examples, priming chatbots. "combining techniques" solo habla de combinacion y chatbots es un intro de priming chatbots.

LLM settings es algo que ellas no tienen que saber para usar prompting directamente, es algo mas de LLMs y no se cuando van a tocar este parte. Diria que empezamos con los tecnicas basicas y ver como expandemos.

**Comment by Davichobits** [comment]
@unjust esta es la estructura para generar los OAs?

prompting:
  title: Uso de ai para generar data, imagenes etc
  links:
    - title: Learning prompting
      url: https://learnprompting.org/

**Comment by Davichobits** [comment]
> Si quedamos con techniques seria : giving instructions, assigning roles, showing examples, priming chatbots. "combining techniques" solo habla de combinacion y chatbots es un intro de priming chatbots.
> 
> Large Language Model settings es algo que ellas no tienen que saber para usar prompting directamente, es algo mas de predicion y como AI funciona abajo. Diria que empezamos enfocando en los tecnicas basicas y ver como expandemos.

```yml
Técnicas de prompting: 
  title: Dando instrucciones
  links:
    - title: Giving instructions
      url: https://learnprompting.org/es/docs/basics/instructions
  title: Asignando roles
  links:
    - title: Assigning roles
      url: https://learnprompting.org/es/docs/basics/roles
  title: Entregando ejemplos
  links:
    - title: Showing examples
      url: https://learnprompting.org/es/docs/basics/roles
  title: prompts de preparación
  links:
    - title: Primming prompts
      url: https://learnprompting.org/docs/basics/priming_prompt
```

**Comment by Davichobits** [comment]
He preguntando a chatGPT que temas recomienda abarcar. Y me arrojó este resultado:

**Técnicas de Prompting:** Enseñar cómo utilizar instrucciones claras y ejemplos efectivos al interactuar con modelos de lenguaje para obtener mejores respuestas.
**Creación de Datos de Entrada:** Mostrar cómo recopilar y preparar datos adecuados para usar como entradas en modelos de IA.
**Tipos de Modelos de Lenguaje:** Introducir los conceptos básicos de modelos de lenguaje, como GPT-3, y cuándo usarlos.
**Interfaz de Usuario (UI) para IA:** Explicar cómo diseñar interfaces de usuario simples para integrar modelos de lenguaje en aplicaciones web.
**Implementación Práctica:** Proporcionar ejemplos básicos de cómo incorporar modelos de lenguaje en aplicaciones web sencillas.
**Evaluación Básica:** Enseñar cómo evaluar la calidad de las respuestas generadas por los modelos de lenguaje de manera simple.
**Consideraciones Éticas Básicas:** Introducir conceptos éticos esenciales relacionados con el uso de IA.
**Recursos Básicos:** Proporcionar recursos y bibliotecas esenciales para trabajar con modelos de lenguaje, como Hugging Face Transformers.

De esto rescato lo de **evaluación básica**, que aún no se si hay alguna técnica. Y **Consideraciones Éticas Básicas:**, lo del resto creo que cumplimos todo.

**Comment by unjust** [comment]
@Davichobits para responder a tus comentarios:

Los learning objectives tienen dos formas:
La hierarquia definido en ingles https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/data.yml
El objetivo en si es siempre ingles y sin espacios entonces por ejemplo `ai-prompting` `ai-prompting/techniques`

Y las traducciones (titles, links) esta en
https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/es.yml
https://github.com/Laboratoria/bootcamp/blob/main/learning-objectives/intl/pt.yml

Con tu ejemplo seria:
``` yaml
ai-prompting:
  title: "IA ..."

ai-prompting/techniques:
  title: "Técnicas de prompting"
  links:
    -...

ai-prompting/techniques/assigning-roles:
  title: "Asignando Roles"
  links:
    - title:  Assigning roles
      url: https://learnprompting.org/es/docs/basics/roles
    - title: ...
 ```
