### ISSUE TITLE
cambiamos/agregamos nuevo objetivo de aprendizaje de "despliegue"

### ISSUE THREAD

**Issue by unjust** [Laboratoria/curriculum#1610]
Ahora solo tenemos 

```
scm/github/gh-pages:
  title: "GitHub: Despliegue con GitHub Pages"
  links:
    - title: Sitio oficial de GitHub Pages
      url: https://pages.github.com/
```

pero vale la pena separar eso de gh pages para acomodar cualquier plataforma?

**Comment by unjust** [comment]
creo ya tenemos, quiza podemos clarificar las plataformas mas pero, creo podemos agregar eso a los proyectos dataverse por ejemplo 
https://github.com/Laboratoria/curriculum/blob/main/learning-objectives/intl/es.yml#L630

**Comment by merunga** [comment]
@unjust de acuerdo con q es necesario generalizarlo fuera de gh-pages. Y tb que quizas ni `cicd` ni `service-deployment` son las mejores categorias. Se podría considerar una webapp como un servicio, pero me pregunto qué otros tipos de deployments deberíamos considerar, y si la categoria no debería llamarse simplemente `deployment`.

Igual no se si es el mejor momento para tener esa otra conversación, asiq mi propuesta seria algo asi:
```yml
cicd/service-deployment/gh-pages:
  title: "GitHub: Despliegue con GitHub Pages"
  links:
    - title: Sitio oficial de GitHub Pages
      url: https://pages.github.com/
cicd/service-deployment/netlify:
  title: "Despliegue con Netlify"
  links:
    - title: Sitio oficial de Netlify
      url: https://www.netlify.com/
cicd/service-deployment/vercel:
  title: "Despliegue con Vercel"
  links:
    - title: Sitio oficial de Vercel
      url: https://vercel.com/
```

**Comment by unjust** [comment]
Vi la converversacion en slack - a mi no me molesta si esta dentro ci/cd pero quiza podemos generar un nuevo.
Lo que no me gusta es pega mucho a las plataformas, porque cambian.

```
cicd/service-deployment:
  title: "Despliegue en una plataforma cloud (GitHub Pages, Vercel, Netlify)"
  links:
    - title: Sitio oficial de GitHub Pages
      url: https://pages.github.com/
    - title: Sitio oficial de Netlify
      url: https://www.netlify.com/
     - title: Sitio oficial de Vercel
         url: https://vercel.com/
 ```

o

```
deployment:
title: "Despliegue en una plataforma cloud (GitHub Pages, Vercel, Netlify)"
  links:
    - title: Sitio oficial de GitHub Pages
      url: https://pages.github.com/
    - title: Sitio oficial de Netlify
      url: https://www.netlify.com/
     - title: Sitio oficial de Vercel
         url: https://vercel.com/
```
